apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "kong-admin-ui.name" . }}-certs
  labels:
    app.kubernetes.io/name: {{ include "kong-admin-ui.name" . }}
    helm.sh/chart: {{ include "kong-admin-ui.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "kong-admin-ui.gen-certs" . ) | indent 2 }}