apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "kong-admin-ui.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "kong-admin-ui.name" . }}
    helm.sh/chart: {{ include "kong-admin-ui.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if .Values.config }}
  {{- end }}